name: Configure, Build and Test
on:
  push:
jobs:
  build-project:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Configure and Build
        uses: threeal/cmake-action@main
        with:
          options: RUN_TESTS=ON
      - name: Test
        uses: threeal/ctest-action@v1.0.0
